syntax = "proto3";
package engine;
service Engine {
  rpc AquireTaskBlock(TaskBlockRequest) returns (TaskBlock);
  rpc AquireTaskReg(empty) returns (TaskRegistry);
  rpc PublishTaskBlock(TaskBlock) returns (empty);
  rpc cgrpc(cgrpcmsg) returns (cgrpcmsg);
  rpc CreateTaskBlock(TaskBlock) returns (TaskBlock);
  rpc DeleteTaskBlock(TaskSelector) returns (empty);
  rpc GetTasks(TaskPageRequest) returns (TaskPage);
  rpc CheckAuth(empty) returns (empty);
  rpc GetMetadata(empty) returns (ServerMetadata);
}
message ServerMetadata {
  string engine_api = 1;
  repeated ModuleInfo mods = 2;
}
message ModuleInfo {
  string mod_id = 1;
  string api_version = 2;
  string rustc_version = 3;
  string mod_version = 4;
}
message TaskSelector {
  TaskState state = 1;
  string namespace = 2;
  string task = 3;
  string id = 4;
}
message TaskBlockSelector {
  repeated TaskBlockSelector selector = 1;
}
message empty {}
enum TaskState {
  QUEUED = 0;
  SOLVED = 1;
  LEASED = 2;
}
message TaskPageRequest {
  string namespace = 1;
  string task = 2;
  uint64 page = 3;
  uint32 pageSize = 4;
  TaskState state = 5;
}
message TaskPage {
  string namespace = 1;
  string task = 2;
  uint64 page = 3;
  uint32 pageSize = 4;
  TaskState state = 5;
  repeated Task tasks = 6;
}
message cgrpcmsg {
  string handler_mod_id = 1;
  string handler_id = 2;
  bytes event_payload = 3;
  string token = 4;
}

message TaskRegistry {
  repeated string tasks = 1; // namespace:task
}

message TaskBlockRequest {
  string task_id = 1; // namespace:task
  uint32 block_size = 2;
}
message Task {
  string id = 4; // the task unique identifier
  bytes task_payload = 1;
  string task_id = 2; // namespace:task
  bytes payload = 3;
}
message TaskBlock {
  repeated Task tasks = 1;
}
